src/example.html, src/fracexpl.js
Reducing the jquery version number
Referring to things via myself instead of this
Defining name and save data globally
=> Fixing a couple of mistakes

src/fracexpl.js
Renames "Draw Mode" to "Iterate Mode" for clarification, as requested by Prof. Eglash.
=> Rename draw mode to iterate mode

src/example.html, src/fracexpl.js
GetUser doesn't error, so check data.id for null
Do close dialog first so even on error dialog goes away
Change style of the project list
=> Fixes To Cloud

src/example.html
* Ron doesn't want it called Fractal Explorer because there is apparently a book under that title.
* MOAR OPTIONS
=> More options for web page

src/fracexpl.js
=> Multiple instances support/bug fixes

src/fracexpl.js
Adds a title to each color button in Edit Mode so that when you hover over it it says what it does, since no one will ever memorize the different color's functions.
=> Adds titles to buttons so hovering says what each color does

src/fracexpl.js
Fixes #23
Thank you for finding this bug!
=> bug fix: Overlapping nodes get pushed away from one another

src/fracexpl.js
Fixes #27
turns out clicking off canvas still needs to be accounted for, doh!
=> Bug Fix: doubleclick->change color->singleclick broke

src/fracexpl.js
Adding style to cloud buttons to keep it visually consistent with rest of program. As requested by Prof. Eglash.
=> Adding style to cloud buttons

src/example.html, src/fracexpl.js
Indicates active segment color by a pink border box around the currently selected segment type in Edit Mode.
=> Active color

src/fracexpl.js
=> added load iteration

src/fracexpl.js
loadIternation#14 is based on master and not cloudSave 
closes #14 closes #33
=> add instance number to iternate level

src/fracexpl.js
Talked with Prof. Eglash, he had requests for how to word green and grey lines in the button title popups.
=> Updating wording after discussion with prof. eglash

src/fracexpl.js
=> Make line cap round

src/fracexpl.js
Closes #45
I can't get this to work on my computer because my chrome won't recognize FractalDraw.load as a new method. So I'd like to push this broken code and just revert if it doesn't work on dev. I think the code should work on dev? 🤞 
Let me know what you think.
=> Remote load from project number in data-seed data property

src/fracexpl.js
=> Fix myself

src/fracexpl.js
Just trying to get a working version.
=> Fix myself2

src/fracexpl.js
Final silly mistake correction
=> Fix myself3

src/fracexpl.js
Break out the load function from loadRemotely
Bind the calls to it
=> Making load DRY

src/fracexpl.js
Adds a check for config.project.id so that we can load using the application_spa.html template in django
=> Adds a check for config.project.id

src/fracexpl.js
YES GIVE ME THE LOVELY TRY CATCH STATEMENT
=> Needs a try-catch
